export const siteConfig = {
  name: "Sheeza Rafique",
  role: "AI Engineer",
  tagline: "Building production ML systems from data to deployment",
  experience: "1+ years",
  email: "sheezarafique266@gmail.com",
  url: "https://portfolio-wheat-phi-46gzbflg0m.vercel.app",
  bio: "AI Engineer with 1+ years of hands-on experience building LLM-powered applications and production machine learning systems. Builds RAG chatbots, MCP agent systems, and real-time voice AI alongside reproducible MLOps pipelines — deploying containerized inference APIs on AWS with full CI/CD automation.",
  interests: [
    "Machine Learning",
    "Deep Learning",
    "LLMs",
    "RAG",
    "MLOps",
    "Cloud",
    "Backend Development",
  ],
  social: {
    github: "https://github.com/Sheeza-Sheeza",
    linkedin: "https://linkedin.com/in/sheezarafique672010238",
    dagshub: "https://dagshub.com/sheezarafique266",
    email: "mailto:sheezaarafique266@gmail.com",
  },
  nav: [
    { label: "About", href: "#about" },
    { label: "Skills", href: "#skills" },
    { label: "Projects", href: "#projects" },
    { label: "Contact", href: "#contact" },
  ],
} as const;
